version: "3"
services:
  app:
    build: ./vgafibweb
    container_name: "vgaweb"
    ports:
      - "80:8822"
    depends_on: 
      - "pg"
  pg:
    image: "postgres:12"
    container_name: "vgaweb_db"
    environment:
      - "POSTGRES_PASSWORD=somepassword"
      - "POSTGRES_USER=root"
      - "POSTGRES_DB=db"
    ports:
      - "5432:5432"
    volumes:
      - ./pg/db_data:/var/lib/postgresql/data